name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1

    - name: Check Python and OS Setup
      run: |
        python -c "import sys; print(sys.version);"
        python -c "import os; print(os.getcwd()); print(os.listdir(os.curdir));"


    - uses: davidcraig/action-wow-lint@v1.0.1
      with:
        path-to-files: '**/*.lua'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        if-no-files-found: error
        path: |
          '_*/*.lua'
          '_*/*.toc'
          '_*/*.xml'
